on: [push]

jobs:
  energyplus_install:
    runs-on: ubuntu-latest
    name: Let us install EnergyPlus
    steps:
      - name: EnergyPlus Install Script
        id: eplus
        uses: myoldmopar/energyplus-install@21d5c38f3d6cbda3d7ac70d8e7d50005c7c5b212
        with:
          version: '24.1.0'
      - name: Get the eplus dir
        run: echo "E+ is available at ${{ steps.eplus.outputs.energyplus_path }}"
