on: [push]
jobs:
  energyplus_install:
    strategy:
      matrix:
        os: [ ubuntu-24.04, macos-12, windows-latest ]
    runs-on: ${{ matrix.os }}
    name: Let us install EnergyPlus
    steps:
      - name: EnergyPlus Install Script
        id: eplus
        uses: myoldmopar/energyplus-install@d52c537fca8a20e82afe6e09fbca1e2b25ecb6eb
        with:
          tag: 'v24.1.0'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
      - name: Get the eplus dir
        run: echo "E+ is available at ${{ steps.eplus.outputs.energyplus_directory }}"
      # - name: Setup upterm session
      #   uses: lhotari/action-upterm@v1
      - name: Try to run E+ with full path
        run: ${{ steps.eplus.outputs.energyplus_directory }}/energyplus -D ${{ steps.eplus.outputs.energyplus_directory }}/ExampleFiles/1ZoneUncontrolled.idf
      - name: Install API Helper
        run: pip install energyplus_api_helpers
      - name: Try to run E+ from API
        run: ./main.py ${{ steps.eplus.outputs.energyplus_directory }}
      
