on: [push]
jobs:
  energyplus_install:
    strategy:
      matrix:
        os: [ macos-12, ubuntu-24.04, windows-latest ]
    runs-on: ${{ matrix.os }}
    name: Let us install EnergyPlus
    steps:
      - name: EnergyPlus Install Script
        id: eplus
        uses: myoldmopar/energyplus-install@00639709a934f8094275f42cdfd5af8839d61808
        with:
          tag: 'v24.1.0'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
      - name: Get the eplus dir
        run: echo "E+ is available at ${{ steps.eplus.outputs.energyplus_directory }}"
      # - name: Setup upterm session
      #   uses: lhotari/action-upterm@v1
      - name: Try to run E+ with full path
        run: ${{ steps.eplus.outputs.energyplus_path }}/energyplus -D ${{ steps.eplus.outputs.energyplus_path }}/ExampleFiles/1ZoneUncontrolled.idf
      # Set up a step that installs energyplus_api_helper(s) and runs a quick API test passing in the e+ path
      # - name: Try to run E+ from PATH
      #   run: energyplus --help
      
