on: [push]
jobs:
  energyplus_install:
    strategy:
      matrix:
        os: [ ubuntu-24.04, macos-12, windows-latest ]
    runs-on: ${{ matrix.os }}
    name: Let us install EnergyPlus
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.12
      - name: EnergyPlus Install Script
        id: eplus
        uses: myoldmopar/energyplus-install@4ca75c3ac221e478acbdfe24360569e246e51264
        with:
          tag: 'v24.1.0'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
      - name: Get the eplus dir
        run: echo "E+ is available at ${{ steps.eplus.outputs.energyplus_directory }}"
      # - name: Setup upterm session
      #   uses: lhotari/action-upterm@v1
      - name: Try to run E+ with full path
        run: ${{ steps.eplus.outputs.energyplus_directory }}/energyplus -D ${{ steps.eplus.outputs.energyplus_directory }}/ExampleFiles/1ZoneUncontrolled.idf
      - name: Install API Helper
        run: pip install energyplus_api_helpers
      - name: Try to run E+ from API
        shell: bash
        run: python main.py ${{ steps.eplus.outputs.energyplus_directory }}
      
