on: [push]

jobs:
  energyplus_install:
    runs-on: ubuntu-latest
    name: Let us install EnergyPlus
    steps:
      - name: EnergyPlus Install Script
        id: eplus
        uses: myoldmopar/energyplus-install@v0.1
        with:
          version: '24.1.0'
      - name: Get the eplus dir
        run: echo "E+ is available at ${{ steps.eplus.outputs.energyplus_path }}"
