on: [push]

jobs:
  energyplus_install:
    runs-on: ubuntu-latest
    name: Let us install EnergyPlus
    steps:
      - name: EnergyPlus Install Script
        id: eplus
        uses: myoldmopar/energyplus-install@0ddcf28b2d9b60a695fd1c177dd69bd0523c35f1
        with:
          version: '24.1.0'
      - name: Get the eplus dir
        run: echo "E+ is available at ${{ steps.eplus.outputs.energyplus_path }}"
      # - name: Setup upterm session
      #   uses: lhotari/action-upterm@v1
      - name: Add E+ dir to path
        run: echo "${{ steps.eplus.outputs.energyplus_path }}" >> $GITHUB_PATH
      - name: Try to run E+ with full path
        run: ${{ steps.eplus.outputs.energyplus_path }}/energyplus -D ${{ steps.eplus.outputs.energyplus_path }}/ExampleFiles/1ZoneUncontrolled.idf
      - name: Try to run E+ from PATH
        run: energyplus --help
        
