on: [push]
jobs:
  energyplus_install:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            hardened: false
          - os: ubuntu-24.04
            hardened: false
          - os: macos-12
            hardened: false
          - os: macos-14
            hardened: false
          - os: windows-latest
            hardened: false
          - os: windows-latest
            hardened: true            
    runs-on: ${{ matrix.os }}
    name: Let us install EnergyPlus
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.12
      - name: EnergyPlus Install Script
        id: eplus
        uses: myoldmopar/energyplus-install@501b5f9b3751135aa1ca43ace0b745d45ed5b6dc
        with:
          tag: 'v24.1.0'
          hardened: ${{ matrix.hardened }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
      - name: Try to run E+ with full path
        run: ${{ steps.eplus.outputs.energyplus_directory }}/energyplus -D ${{ steps.eplus.outputs.energyplus_directory }}/ExampleFiles/1ZoneUncontrolled.idf
      - name: Install API Helper
        run: pip install energyplus_api_helpers
      - name: Try to run E+ from API
        run: python main.py ${{ steps.eplus.outputs.energyplus_directory }}
      
